/*

  This program is part of the TACLeBench benchmark suite.
  Version 2.0

  Name: cover

  Author: unknown

  Function: A program for testing many paths generated by switch-case
            statements.

  Source: MRTC
          http://www.mrtc.mdh.se/projects/wcet/wcet_bench/cover/cover.c

  Original name: cover

  Changes: See ChangeLog.txt

  License: may be used, modified, and re-distributed freely

*/


/*
  Forward declaration of functions
*/

void cover_init( void );
void cover_main( void );
int cover_return( void );
int cover_swi10( int );
int cover_swi50( int );
int cover_swi120( int );


/*
  Declaration of global variables
*/

static volatile int cover_cnt;


/*
  Initialization- and return-value-related functions
*/

void cover_init( void )
{
  cover_cnt = 0;
}


int cover_return( void )
{
  return cover_cnt - 180;
}


int increment_c(int i){
  i++;
  return i;
}

/*
  Core benchmark functions
*/

int cover_swi120(int c) {
  int i;
  _Pragma("loopbound min 120 max 120")
  for (i = 0; i < 1; i++) {
      c = increment_c(c);
  }
  return c;
}


int cover_swi50(int c) {
  int i;
  _Pragma("loopbound min 50 max 50")
  for (i = 0; i < 1; i++) {
      c = increment_c(c);
  }
  return c;
}




int cover_swi10(int c) {
  int i;
  _Pragma("loopbound min 10 max 10")
  for (i = 0; i < 1; i++) {
      c = increment_c(c);
  }
  return c;
}


void _Pragma( "entrypoint" ) cover_main( void )
{
  cover_cnt = cover_swi10( cover_cnt );

  cover_cnt = cover_swi50( cover_cnt );

  cover_cnt = cover_swi120( cover_cnt );
}


/*
  Main function
*/

int main( void )
{
  cover_init();
  cover_main();

  return cover_return();
}
